### ISSUE TITLE
More command not filling up item to max stack

### ISSUE THREAD

**Issue by CKylinMC** [WhiteXZ/EssentialsPlus#21]
When I using "/more", It only doubles the count of items in my hand, which is not like the descriptions said: "Maximizes item stack of held item."

https://github.com/QuiCM/EssentialsPlus/blob/dd7352526df2a2fa4a44048b41ab9c76203e9ab8/EssentialsPlus/Commands.cs#L436

I think it may should be like this:
```csharp
e.Player.GiveItem(item.type, amtToAdd); // not item.stack
```

and L421 should be same:
https://github.com/QuiCM/EssentialsPlus/blob/dd7352526df2a2fa4a44048b41ab9c76203e9ab8/EssentialsPlus/Commands.cs#L421

-----

And, is there any way to clone a weapon or armor item?

**Comment by msva** [comment]
@QuiCM can you create a new release with this fix, please?

**Comment by tannertechnology** [comment]
@msva You can grab a recent build from github actions now. https://github.com/QuiCM/EssentialsPlus/suites/6994455713/artifacts/274088160
