### ISSUE TITLE
Unable to connect to any of the specified MySQL hosts.

### ISSUE THREAD

**Issue by mylemans** [WhiteXZ/EssentialsPlus#7]
I'm getting the following

> [03/27/16 14:36:20] [Server API] Warning: Plugin "EssentialsPlus" has had an unhandled exception thrown by one of its GameInitialize handlers: 
> MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
>    at MySql.Data.MySqlClient.NativeDriver.Open()
>    at MySql.Data.MySqlClient.Driver.Open()
>    at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
>    at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
>    at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
>    at MySql.Data.MySqlClient.MySqlPool.GetConnection()
>    at MySql.Data.MySqlClient.MySqlConnection.Open()
>    at TShockAPI.DB.DbExt.QueryReader(IDbConnection olddb, String query, Object[] args)
>    at TShockAPI.DB.SqlTableCreator.GetColumns(SqlTable table)
>    at TShockAPI.DB.SqlTableCreator.EnsureTableStructure(SqlTable table)
>    at EssentialsPlus.Db.MuteManager..ctor(IDbConnection db)
>    at EssentialsPlus.EssentialsPlus.OnInitialize(EventArgs e)
>    at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)

I'm running terraria server from a VM and the MySQL is on the 'host' of the VM. It is properly configured for the server itself, as it did succeed in creating its core database structure + it also stored users.

Any ideas?

**Comment by mylemans** [comment]
Ignore this. Would have been nice if you told at start up that it needs to be configured..

**Comment by WhiteXZ** [comment]
Hi, I've just added the suggested change :)
